# fly.toml app configuration file generated for green-snowflake-5800 on 2023-11-15T19:11:17-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-snowflake-5800"
primary_region = "atl"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
